export class Comprobante {
  constructor(
    public id?: number,
    public tipodoc?: string,
    public Ruc?: string,
    public Numero?: string,
    public Identificacion?: string,
    public Fecha?: string,
    public Direccion?: string,
    public Telefono?: string,
    public Email?: string,
    public SubtotalIva?: string,
    public SubtotalIva0?: string,
    public SubtotalNoIva?: string,
    public SubtotalExentoIva?: string,
    public Subtotal?: string,
    public Descuento?: string,
    public Ice?: string,
    public Irbpnr?: string,
    public Iva?: string,
    public Propina?: string,
    public Total?: string,
    public Anulada?: string,
    public Xml?: string,
    public XmlFirmado?: string,
    public XmlSri?: string,
    public ClaveAcceso?: string,
    public NoAutorizacion?: string,
    public FechaAutorizacion?: string,
    public Estado?: string,
    public Origen?: string,
    public Info?: string,
    public Electronica?: string,
    public Sincronizado?: string,
    public Procesado?: string,
    public WsStatus?: string,
    public Bandera?: string,
    public Trace?: string,
    public Marca?: string,
    public Anulado?: string,
    public detalles?: string[],
  ) {}
}
